---
 - hosts: pi
   vars:
     - provision_password: '$6$2nZ5CA..Oz$nO27UjmxuGErdQZFHvo2OIGmJYfD7rzPaRNeOeQQRqmZtz5A1hIv7tMhuHbNYJH1XIUIxzKK2NQHsDlq/ojdJ1'
   gather_facts: no
   remote_user: provision
   become: true
 
   tasks:
 
   - name: Add a new user named provision
     user:
          name=provision
          password={{ provision_password }}
 
   - name: Add provision user to the sudoers
     copy:
          dest: "/etc/sudoers.d/provision"
          content: "provision  ALL=(ALL)  NOPASSWD: ALL"

   - name: Install default or required packages
     package:
       name:
         - git
#         - powerline-fonts
#         - fzf
         - atop
         - htop
         - iftop
       state: present
     become: yes
     tags: install_default_packages 

   - name: make sure git is installed
     package:
       name: git
       state: present

   - name: fetch fzf from github
     git:
       repo: 'https://github.com/junegunn/fzf.git'
       dest: /tmp/fzf/
       version: HEAD # latest

   - name: Run install script
     become: yes
#     script: /tmp/fzf/install --no-key-bindings --no-completion --no-update-rc
     script: /tmp/fzf/install --key-bindings --completion --update-rc
